baseURL = 'https://evandro.org/'
languageCode = 'pt'
title = 'Em Desconstrução'
theme = 'ananke'
disqusShortname = 'emdesconstrucao'
googleAnalytics = 'G-55LRX8SYX4'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
#   description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3


[[params.ananke_socials]]
    name = "instagram"
    url = "https://www.instagram.com/j_evandro" 

[[params.ananke_socials]]
    name = "twitter"
    url = "https://twitter.com/evandro"

[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/evandrojr"    

    